### PR TITLE
Extend pixelmatch options

### LINKED ISSUE #113: [Enhancement] Pixelmatch options
Hello,
Would be nice to have possibility to pass some variables to pixelmatch f.e.`includeAA` or `diffColor` because not always default colors are best solution. 

Also can You tell me please, why to count percentage You are using ** 0.5 ?
https://github.com/mjhea0/cypress-visual-regression/blob/993b2e8f2e3887a86f0208ef082b311dce5bf504/src/plugin.js#L104

### PR DESCRIPTION
**Pull request by Zaista**
This PR will:

- enable overriding default pixelmatch options, like threshold (fixes #113 and #263 
- moved plugin options preparation logic to `command.ts` file and cleaned it up. The logic on which it works now is: set default values, then override values set in e2e file, then override values set in env variables, then lastly override any options set in the command itself
- extended tests to check this logic
- minor other improvements

### CODE REVIEW

File: src/command.ts [hunk 1]
```diff
@@ -29,104 +36,116 @@ export type CypressConfigEnv = {
...
   }
 
-  if (screenshotOptions?.failSilently !== undefined) {
-    options.failSilently = screenshotOptions.failSilently
+  // secondly, override values provided in e2e support file
+  if (screenshotOptions.pixelmatchOptions !== undefined) {
+    options.pluginOptions.pixelmatchOptions = screenshotOptions.pixelmatchOptions
+  }
+  // TODO refactor this in next release, separate plugin vs screenshot properties
+  options.screenshotOptions = { ...screenshotOptions, ...commandOptions }
```
Comment (Zaista) [inline src/command.ts:124]: This annoys me, and would like to change it in the next breaking change release (as this will also be a breaking change)
It will make it much easier to maintain this if we split the options up:
```
addCompareSnapshotCommand({
  pluginOptions: {
    errorThreshold: 0,
    failSilently: false,
  },
  pixelmatchOptions: {
    threshold: 0.1
  },
  screenshotOptions: {
    capture: 'fullPage'
  }
})
```

File: src/command.ts [hunk 2]
```diff
@@ -29,104 +36,116 @@ export type CypressConfigEnv = {
...
-  }
-  multipart: boolean
-  pixelRatio: number
-  takenAt: string
-  name: string
-  blackout: string[]
-  duration: number
-  testAttemptIndex: number
-}
+type TakeScreenshotProps = Partial<Cypress.ScreenshotOptions> & { path: string }
```
Comment (area73) [inline src/command.ts:39]: Do you want to make it partial? that means that "all" the props defined in Cypress.ScreenshotOptions will be optional

Also looking at the definition of [Cypress.ScreenshotOptions ](https://github.com/cypress-io/cypress/blob/ebbf7b1bdca49e509d22738c7b3ba92b26b065f3/cli/types/cypress.d.ts#L3669)

It looks like you want to use the types defined under `onAfterScreenshot` which is a function that accepts as a second argument the object that you are typing, but I don't know if there is an easy way to type it like that.

Because you can use a type like  `Cypress.ScreenshotOptions['onAfterScreenshot']` but that will return a function and what you need to type is the second parameter passing to that function, so you can either try to find aTS way to type that or just keep the old typeDefinitiopn and add the path

File: src/command.ts [hunk 3]
```diff
@@ -29,104 +36,116 @@ export type CypressConfigEnv = {
...
-        errorThreshold = screenshotOptions?.errorThreshold
-      }
-      let regressionOptions: ScreenshotOptions
-      if (typeof commandOptions === 'object') {
-        regressionOptions = { ...screenshotOptions, ...commandOptions }
-        if (commandOptions.errorThreshold !== undefined) {
-          errorThreshold = commandOptions.errorThreshold
-        }
+
+      const realScreenshotOptions = { ...screenshotOptions }
```
Comment (area73) [inline src/command.ts:55]: I can't figure out why you need to declare realScreenshotOptions, I don't see that you are mutating screenshotOptions

File: src/command.ts [hunk 4]
```diff
@@ -29,104 +36,116 @@ export type CypressConfigEnv = {
...
+      let realCommandOptions
+      if (typeof commandOptions === 'number') {
+        realCommandOptions = { errorThreshold: commandOptions }
       } else {
-        regressionOptions = { ...screenshotOptions }
-        if (commandOptions !== undefined) {
-          errorThreshold = commandOptions
-        }
+        realCommandOptions = { ...commandOptions }
       }
```
Comment (area73) [inline src/command.ts:63]: I think you can simplify this code (from line 57 to line 62)

```
const realCommandOptions = (typeof commandOptions === 'number' )
  ? { errorThreshold: commandOptions }
  : commandOptions
```

File: src/command.ts [hunk 5]
```diff
@@ -29,104 +36,116 @@ export type CypressConfigEnv = {
...
-              `The 'type' environment variable is unknown. Expected: 'regression' or 'base' instead of '${
-                visualRegressionOptions.type as string
-              }'`
-            )
+      return takeScreenshot(subject, folderAndName, visualRegressionOptions.screenshotOptions).then(
+        (screenShotProps) => {
+          // Screenshot already taken
+          visualRegressionOptions.screenshotAbsolutePath = screenShotProps.path
+          visualRegressionOptions.spec = Cypress.spec
+          switch (visualRegressionOptions.type) {
```
Comment (area73) [inline src/command.ts:73]: I know it's not cool to use `switch` statements but I love them 👌👌

**Review by area73 — COMMENTED** [review]
Minor comments.
Nice job 👍

File: src/command.ts (hunk 3 above)
Comment (Zaista) [reply src/command.ts:55]: `screenshotOptions` can be `undefined`, and if I do this, it assures at least `{}`. I'm not a fan of it also, open for suggestions

File: src/command.ts (hunk 2 above)
Comment (Zaista) [reply src/command.ts]: Thanks for pushing this, it annoyed me as well. In the end, I saw that we don't need a type at all, seems that Cypress fixed their type:
image

File: src/command.ts (hunk 3 above)
Comment (Zaista) [reply src/command.ts]: I renamed it to `screenshotOptionsObject`, and left a comment to explain the purpose. Should be more friendly now

**Review by area73 — APPROVED** [review]
🚀
